### ISSUE TITLE
cudnn doesn't support kernel-3 stride-2 pad-1

### ISSUE THREAD

**Issue by kitofans** [soumith/cudnn.torch#104]
I've been looking around to see if this is intended or I'm just doing something stupid, but it's really hard to find official docs on what cudnn supports and what it doesn't support. but, the following code:

```
require 'cudnn'
x = cudnn.SpatialConvolution(3,16,3,3,2,2,1,1)

x:cuda()
x:forward(torch.rand(3,32,32):cuda())

```
results in "Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED"

So i assume it has something to do with the stride not matching the kernel size. I haven't gone through and seen what fails and what doesn't, if you know where to find a list of supported convolution arguments from cudnn, would appreciate being pointed in the right direction. Also, i'd be interested to see that list for cudnn v4 as well. 

Anyways, if it's just cudnn's fault, that's fine, but I think it might make sense to list this on the readme, since nn's SpatialConvolution does support these convolution arguments, so cudnn is not really fully compatible with nn.

**Comment by szagoruyko** [comment]
you should update to V4, it works.

**Comment by fmassa** [comment]
CUDNN V2 works for me as well.

**Comment by soumith** [comment]
Now that CuDNN R4 final version is released, closing this issue.
