### ISSUE TITLE
Cudnn/Pooling.lua, gradinput=nill 

### ISSUE THREAD

**Issue by skrealworld** [soumith/cudnn.torch#130]
Hi, 
I am having following error while using cudnn v4 &nividia 7.5 on K40 GPU. 
  
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-5709/cutorch/lib/THC/THCGeneral.c line=591 error=8 : invalid device function
/home/sk1846/torch/install/bin/luajit: /home/sk1846/torch/install/share/lua/5.1/cudnn/Pooling.lua:57: cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-5709/cutorch/lib/THC/THCGeneral.c:591
stack traceback:
        [C]: in function 'resizeAs'
        /home/sk1846/torch/install/share/lua/5.1/cudnn/Pooling.lua:57: in function 'createIODescriptors'
        /home/sk1846/torch/install/share/lua/5.1/cudnn/Pooling.lua:88: in function 'updateOutput'
        /home/sk1846/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        /home/sk1846/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'

**Comment by szagoruyko** [comment]
can you provide a short script to reproduce?

**Comment by skrealworld** [comment]
Actually, I updated my nn and now it is throwing this error. 

/home/sk1846/torch/install/bin/luajit: ...46/torch/install/share/lua/5.1/nn/BatchNormalization.lua:109: attempt to call field 'BatchNormalization_updateOutput' (a nil value)
stack traceback:

I am using imagenetMultiGPU code with 10x224x224 data.

**Comment by soumith** [comment]
you need to reinstall cunn as well. luarocks install cunn

**Comment by skrealworld** [comment]
Thanks a ton, it solved the problem. I didn't know you have update torch and nn module separately.  
Thanks again.
