### ISSUE TITLE
cudnn5 load path in osX El Capitan

### ISSUE THREAD

**Issue by floringogianu** [soumith/cudnn.torch#178]
I copied the three `libcudnn` libs provided by nvidia in `/usr/local/cuda/lib/` where the rest of the `cuda` libraries are symlinked. I did this because simply exporting the current path to `DYLD_LIBRARY_PATH` might not work anymore as suggested in #111 .

So currently both `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` are: `/Users/florin/torch/install/lib:/usr/local/cuda/lib:` However `require cudnn` still throws `libcudnn (R5) not found in library path.` `cutorch` and `cunn` seem to be working fine.

I also checked the file permissions are the same as for the symlinks.

Any suggestions?

**Comment by DougFirErickson** [comment]
The method of renaming the three cuDNN v5 files and moving them into `/usr/local/lib/` worked for me on OS X 10.9. I also copied the cudnn.h header file to `/usr/local/cuda/include/` for good measure.

**Comment by Imperssonator** [comment]
This is unrelated to this specific issue but will hopefully be helpful for somebody in the future...

I was trying to run Facebook's new open source DeepMask and SharpMask under Torch on OSX 10.11 with cudnn 5, and running

`th computeProposals.lua $DEEPMASK/pretrained/deepmask`

gave me

`/Users/Imperssonator/torch/install/bin/luajit: ...Imperssonator/torch/install/share/lua/5.1/trepl/init.lua:384: ...Imperssonator/torch/install/share/lua/5.1/trepl/init.lua:384: .../Imperssonator/torch/install/share/lua/5.1/cudnn/ffi.lua:1597: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)`

I moved `libcudnn.dylib`, `libcudnn.5.dylib`, and `libcudnn_static.a` to `usr/local/lib/` and that worked for me, so thanks.

**Comment by vinhqdang** [comment]
I am working with different project from Facebook, and the way presented by @Imperssonator works perfectly. Maybe they shared common configurations.

**Comment by soumith** [comment]
an alternative is to do:
export CUDNN_PATH=[path to your so files]
th [your script]

**Comment by vinhqdang** [comment]
Hi,

How can you got the SO files?

I downloaded CuDNN for Mac OS (version 5.1 for CUDA 8.0 today) and get only three files:

```
libcudnn.5.dylib*  libcudnn.dylib@    libcudnn_static.a
```

Of course, there is another file ``cudnn.h`` but that's all.

**Comment by soumith** [comment]
for OSX it is dylib, Linux it is so.
