### ISSUE TITLE
Potential CuDNN 5.1 issue

### ISSUE THREAD

**Issue by iassael** [soumith/cudnn.torch#333]
Trying to access any function on <RNN>:reset() or :weights() causes an error. If I have some time in the next weeks I'll try to see the differences in CuDNN 5.1 API.

```
THCudaCheck FAIL file=/opt/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu line=35 error=8 : invalid device function
/opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/cudnn/RNN.lua:67: cuda runtime error (8) : invalid device function at /opt/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu:35
stack traceback:
        [C]: in function 'zero'
        /opt/torch/install/share/lua/5.1/cudnn/RNN.lua:67: in function 'reset'
        /opt/torch/install/share/lua/5.1/cudnn/RNN.lua:41: in function '__init'
        /opt/torch/install/share/lua/5.1/cudnn/BGRU.lua:4: in function '__init'
        /opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
        [C]: in function 'BGRU'
```

**Comment by soumith** [comment]
invalid device function usually points out to an unsupported GPU. What GPU are you using?

**Comment by iassael** [comment]
This was speed of light (as always). Hmm we are using P100, this error only started happening after moving to CuDNN 5.1, where I also get nil values returned from `cudnnGetFilterNdDescriptor` calls. Did you encounter any issues with 5.1?

**Comment by soumith** [comment]
i dont have a P100 :)
i personally haven't used the RNN stuff much, but I know Natalia has been using cudnn.torch's RNN API on P100 for some language modeling stuff, and it works.

Do tests pass for you? i.e. https://github.com/soumith/cudnn.torch/blob/master/test/test_rnn.lua ?

**Comment by iassael** [comment]
Everything gets an error, it used to work like a charm until CuDNN 5.0, which version is she using? I'll try to do some debugging in the wkd.

**Comment by soumith** [comment]
she uses 5.1 too afaik.
Since you have P100, you could also try out R6 RC via the R6 branch. I have no idea what state it is in.

**Comment by ngimel** [comment]
5.1 worked for me the last time I checked (couple weeks back). There were no changes in 5.1 (compared to 5) in rnn related apis (other than a fix to a nondeterministic dropout behavior).

**Comment by iassael** [comment]
@soumith I switched to R6 RC but I get the same behavior. I also tried it with a Maxwell arch, where I get errors when I try to access the :weights(). I'll have a closer look in the wkd.

**Comment by ngimel** [comment]
@iassael, On master, commits #323 and #324 break things for me (apparently, tonumber does not work on Ubuntu16.04 and luajit the way it does for commit author), with those commits reverted :weights gives expected outputs. R6 though does not have those commits and works for me as is. And btw I'm on P100 and I don't have  invalid device errors - may be something wrong with your cutorch install, or your cudnn 5.1 is not cuda 8.0 (there are different versions for cuda 7.5 and cuda 8.0)?

**Comment by borisfom** [comment]
@ngimel, @soumith: commits #323 and #324 break things on Ubuntu 14 as well. Has nothing to do with cudnn 5.1

**Comment by borisfom** [comment]
Looks like it has to do with Lua 5.2 vs. Lua 5.1  though - @soumith, how should we fix that ?

**Comment by soumith** [comment]
fixed in master

**Comment by harjatinsingh** [comment]
I am having the same issue. I just switched form GTX970 to GTX1080 Ti. What is the fix ?
