### ISSUE TITLE
OSX cudnn wont load after update to latest torch

### ISSUE THREAD

**Issue by sneiman** [soumith/cudnn.torch#37]
Running on Yosemite. All NVIDIA components current. Recent update of torch installation. Upon load of cudnn I get:
/Users/seth/Dev/torch/install/bin/luajit: /Users/seth/Dev/torch/install/share/lua/5.1/trepl/init.lua:363: /Users/seth/Dev/torch/install/share/lua/5.1/trepl/init.lua:363: /Users/seth/Dev/torch/install/share/lua/5.1/cudnn/init.lua:26: Error in CuDNN: CUDNN_STATUS_INTERNAL_ERROR

This is not stopping me from anything - but it is new, thought you'd like to know.

**Comment by soumith** [comment]
Hmmm, I dont have an OSX system to reproduce.... Checked on Linux though with a fresh install, seems fine.

**Comment by szagoruyko** [comment]
I have this issue too on OS X, guess they will fix it in R3

**Comment by sneiman** [comment]
Yes – works fine for me on ubuntu as well.

S

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by sneiman** [comment]
I fixed this - my error I believe. An older restore script (mine) set env vars to CUDA 6.5. Fixing this to point to 7.0 R2 and reinstalling seems to have resolved the problem.

**Comment by sneiman** [comment]
Unfortunately, my fix is not stable - sometimes it works and some times it doesn't.

**Comment by sneiman** [comment]
After some more experiments I am all but certain that this is a gpu memory issue - not a bug.

**Comment by soumith** [comment]
@sneiman looks like somehow #38 fixed this. maybe on OSX there's a lower cudnn handle limit than linux. weird.

**Comment by sneiman** [comment]
Exacerbated by the fact that there is so little gpu ram on a macbook pro.
This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.
