### ISSUE TITLE
Problem with nn.Replicate(1)

### ISSUE THREAD

**Issue by xonobo** [soumith/cudnn.torch#74]
In order to use the nn.SpatialBatchNormaliztion during test I need to simulate a batch (4D) from a single sample image (3D), i.e make a 1xNxM --> 1x1xNxM tensor. I use nn.Replicate(1) for this but the cudnn.SpatialConvolution complains about its input. Here is the code to reproduce the error:

m = nn.Sequential()
m:add(nn.Replicate(1))
m:add(cudnn.SpatialConvolution(1,3,5,5))
m:cuda()
m:forward(torch.rand(1,7,7):cuda())

I got this:
/torch/install/share/lua/5.1/cudnn/init.lua:58: Error in CuDNN: CUDNN_STATUS_BAD_PARAM
stack traceback:
	[C]: in function 'error'
	/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
	/torch/install/share/lua/5.1/cudnn/init.lua:76: in function 'toDescriptor'
	/torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:108: in function 'createIODescriptors'
	/torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:339: in function 'updateOutput'
	/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	[string "_RESULT={m:forward(torch.rand(1,7,7):cuda())}"]:1: in main chunk
	[C]: in function 'xpcall'
	/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
	/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670

But this works perfect
m.modules[2]:forward(torch.rand(1,1,7,7):cuda()):size()

By the way the nn version also works
m.modules[2] = nn.SpatialConvolution(1,3,5,5)
m:forward(torch.rand(1,7,7):cuda()):size()

Any workaround for the batch simulation is also welcome.

**Comment by fmassa** [comment]
@xonobo can't you just take your input and do
```lua
input=input:view(1,input:size(1),input:size(2),input:size(3))
```
 before feeding the input to the network ?

**Comment by mys007** [comment]
Some time ago I observed that cudnn doesn't like 0-strides, I think this is the case. fmassa's solution should work.

**Comment by xonobo** [comment]
I tried this but now gives an assertion fail

m:forward(torch.rand(1,7,7):view(1,1,7,7):cuda())
/torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:92: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:92: in function 'createIODescriptors'
	/torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:339: in function 'updateOutput'
	/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	[string "_RESULT={m:forward(torch.rand(1,7,7):view(1,1..."]:1: in main chunk
	[C]: in function 'xpcall'
	/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
	/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk

By the way I want to handle this dummy resizing in the model. Since the input sizes of the images may vary I could not use nn.View.

**Comment by fmassa** [comment]
@xonobo remove the `nn.Replicate` from your network.
Also, no need to use the `nn.View` module, apply the view directly to the input data, this way it's independent on the input size

**Comment by xonobo** [comment]
ok forgot to remove the replicate. Now it works.

Thanks for the solution. This is not what I exactly want but handle the resizing of input before feeding to the model.

**Comment by fmassa** [comment]
if you absolutely want to have the `nn.Replicate(1)` in your network, add also just after it a `nn.Copy(nil,nil,true)`, and then you can feed the input without viewing it. But it won't handle the case where the input is already batched.
